backend:
  name: github
  repo: p2pu/facilitate-course
  branch: gh-pages
media_folder: img/
collections:
  - name: "Orientation" # Used in routes, e.g., /admin/collections/blog
    label: "Orientation" # Used in the UI
    folder: "modules/Orientation/_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
